FROM node:18-alpine AS builder

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

RUN npm build

FROM nginx:1

COPY --from=builder /app/dist /usr/share/nginx/html