services:
  backend:
    image: golang:1.21
    volumes:
      - ./backend:/app
      - ./backend/go-build:/root/.cache/go-build
    working_dir: /app
    ports:
      - 5174:8090
    command:
      - /bin/sh
      - -c
      - |
        go run -v . serve --http=0.0.0.0:8090
  frontend:
    image: node:18
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - 5173:5173
    command:
      - /bin/sh
      - -c
      - |
        yarn dev --host
    depends_on: 
      - backend